"use client";
import { FormEvent, useState } from "react";
import { CalendarDays, Mail, Plus } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";
import { WorkspaceFrame } from "@/app/components/WorkspaceFrame";
type Client = { id: number; company_name: string };
type ClientsResponse = { data: Client[] };
export function AppointmentForm() {
  const queryClient = useQueryClient(); const [title, setTitle] = useState(""); const [clientId, setClientId] = useState(""); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [attendees, setAttendees] = useState(""); const [description, setDescription] = useState(""); const [sendEmail, setSendEmail] = useState(false); const [emailTo, setEmailTo] = useState(""); const [emailSubject, setEmailSubject] = useState(""); const [emailBody, setEmailBody] = useState(""); const [notice, setNotice] = useState("");
  const clients = useQuery<ClientsResponse>({ queryKey: ["appointment-clients"], queryFn: async () => (await apiClient.get("/v1/clients", { params: { per_page: 100 } })).data });
  const createEvent = useMutation({ mutationFn: () => apiClient.post("/v1/google/calendar", { client_id: clientId ? Number(clientId) : null, title, description: description || null, starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString(), attendees: attendees.split(",").map(email => email.trim()).filter(Boolean), send_email: sendEmail, email_to: emailTo || undefined, email_subject: emailSubject || title, email_body: emailBody || description || undefined }), onSuccess: () => { setNotice("Appointment created successfully."); setTitle(""); setClientId(""); setStartsAt(""); setEndsAt(""); setAttendees(""); setDescription(""); setSendEmail(false); setEmailTo(""); setEmailSubject(""); setEmailBody(""); queryClient.invalidateQueries({ queryKey: ["calendar-events"] }); }, onError: () => setNotice("Could not create the appointment. Connect Google Calendar first.") });
  function submit(event: FormEvent) { event.preventDefault(); createEvent.mutate(); }
  return <WorkspaceFrame title="Add appointment" eyebrow="Calendar"><main className="standalone-page"><div className="content"><div className="page-intro"><div><p className="eyebrow">New appointment</p><h2>Schedule a meeting</h2><p>Choose a client or leave it as a personal appointment.</p></div><CalendarDays size={25} /></div>{notice && <div className="notice">{notice}</div>}<section className="panel"><div className="panel-head"><div><p className="eyebrow">Appointment details</p><h3>Create a calendar event</h3></div><Plus size={20} /></div><form className="mail-compose" onSubmit={submit}><label>Appointment title<input required value={title} onChange={e => setTitle(e.target.value)} placeholder="Client review call" /></label><label>Client<select value={clientId} onChange={e => setClientId(e.target.value)}><option value="">Personal / no client</option>{clients.data?.data?.map(client => <option value={client.id} key={client.id}>{client.company_name}</option>)}</select></label><div className="form-grid"><label>Starts at<input required type="datetime-local" value={startsAt} onChange={e => setStartsAt(e.target.value)} /></label><label>Ends at<input required type="datetime-local" value={endsAt} onChange={e => setEndsAt(e.target.value)} /></label></div><label><span><Mail size={14} /> Calendar invite emails</span><input value={attendees} onChange={e => setAttendees(e.target.value)} placeholder="client@example.com, colleague@example.com" /><small>These addresses receive the Google Calendar invitation.</small></label><label>Notes<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Agenda, follow-up points, or meeting link…" rows={5} /></label><label className="email-toggle"><input type="checkbox" checked={sendEmail} onChange={e => setSendEmail(e.target.checked)} /> Send a separate custom email</label>{sendEmail && <><label>Email recipient<input type="email" value={emailTo} onChange={e => setEmailTo(e.target.value)} placeholder="Blank = selected client's primary contact, or my email" /></label><label>Email subject<input value={emailSubject} onChange={e => setEmailSubject(e.target.value)} placeholder={title || "Appointment details"} /></label><label>Email content<textarea required value={emailBody} onChange={e => setEmailBody(e.target.value)} placeholder="Write the email content…" rows={7} /></label></>}<button className="primary-button" disabled={createEvent.isPending}>{createEvent.isPending ? "Creating…" : "Create appointment"}</button></form></section></div></main></WorkspaceFrame>;
}
