"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Mail, Send } from "lucide-react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";
import { WorkspaceFrame } from "@/app/components/WorkspaceFrame";
export default function SendEmailPage() {
  const [to, setTo] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [notice, setNotice] = useState(""); const [clientId, setClientId] = useState(""); const [clientSearch, setClientSearch] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("to")) setTo(params.get("to") || ""); if (params.get("subject")) setSubject(params.get("subject") || ""); }, []);
  const clients = useQuery<{ data: { id: number; company_name: string }[] }>({ queryKey: ["send-email-clients"], queryFn: async () => (await apiClient.get("/v1/clients", { params: { per_page: 100 } })).data });
  const contacts = useQuery<{ data: { contactable_type: string; contactable_id: number; email?: string; is_primary?: boolean }[] }>({ queryKey: ["send-email-contacts"], queryFn: async () => (await apiClient.get("/v1/contacts", { params: { per_page: 200 } })).data });
  const filteredClients = useMemo(() => (clients.data?.data || []).filter(client => client.company_name.toLowerCase().includes(clientSearch.toLowerCase())), [clients.data, clientSearch]);
  function chooseClient(value: string) { setClientId(value); const contact = contacts.data?.data?.filter(item => item.contactable_type === "client" && item.contactable_id === Number(value) && item.email).sort((a, b) => Number(b.is_primary) - Number(a.is_primary))[0]; if (contact?.email) setTo(contact.email); }
  const send = useMutation({ mutationFn: () => apiClient.post("/v1/google/gmail/send", { to, subject, body }), onSuccess: () => { setNotice("Email sent successfully."); setTo(""); setSubject(""); setBody(""); }, onError: () => setNotice("Email could not be sent. Connect Gmail first.") });
  function submit(event: FormEvent) { event.preventDefault(); send.mutate(); }
  return <WorkspaceFrame title="Send email" eyebrow="Gmail"><main className="standalone-page"><div className="content"><div className="page-intro"><div><p className="eyebrow">Outgoing mail</p><h2>Send a new email</h2><p>Search for one of your clients or enter an email manually.</p></div><Mail size={25} /></div>{notice && <div className="notice">{notice}</div>}<section className="panel"><div className="panel-head"><div><p className="eyebrow">Compose</p><h3>New message</h3></div><Send size={20} /></div><form className="mail-compose" onSubmit={submit}><label>Search clients<input value={clientSearch} onChange={e => setClientSearch(e.target.value)} placeholder="Type a company name…" /></label><label>Choose client<select value={clientId} onChange={e => chooseClient(e.target.value)}><option value="">No client / choose manually</option>{filteredClients.map(client => <option value={client.id} key={client.id}>{client.company_name}</option>)}</select></label><label>To<input required type="email" value={to} onChange={e => setTo(e.target.value)} placeholder="client@example.com" /></label><label>Subject<input required value={subject} onChange={e => setSubject(e.target.value)} placeholder="Subject" /></label><label>Message<textarea required value={body} onChange={e => setBody(e.target.value)} placeholder="Write your message…" rows={12} /></label><button className="primary-button" disabled={send.isPending}>{send.isPending ? "Sending…" : "Send email"}</button></form></section></div></main></WorkspaceFrame>;
}
