"use client";
import { FormEvent, useState } from "react";
import { apiClient } from "@/lib/api-client";

export default function ResearchPage() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<any[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); try { const r = await apiClient.post("/v1/ai/lead-search", { query }); setResults(r.data.results || []); setMessage(`${(r.data.results || []).length} prospects found. Review sources before saving as leads.`); } catch (e: any) { setMessage(e?.response?.data?.message || "Search provider is not configured."); } finally { setBusy(false); } }
  return <main className="main standalone-page"><div className="content"><div className="page-intro"><p className="eyebrow">Prospecting intelligence</p><h1>AI Lead Research</h1><p>Search for companies, review evidence and save only qualified prospects to your CRM.</p></div><section className="panel"><form onSubmit={submit}><label>What companies are you looking for?<textarea value={query} onChange={e => setQuery(e.target.value)} required minLength={3} placeholder="مثال: شركات تستورد مواد غذائية في جدة وتحتاج شحن بحري" /></label><button className="primary-button" disabled={busy}>{busy ? "Searching…" : "Search the web"}</button></form>{message && <div className="notice">{message}</div>}</section><section className="ai-results">{results.map(item => <article className="panel" key={item.id}><h3>{item.company_name}</h3><p>{item.description}</p><small>Confidence: {item.confidence_score}% · Lead score: {item.lead_score}</small>{item.source_url && <p><a href={item.source_url} target="_blank" rel="noreferrer">Open source evidence</a></p>}</article>)}</section></div></main>;
}
